### ISSUE TITLE
Optional int? parameter set as null not working

### ISSUE THREAD

**Issue by doorman02** [paulcbetts/refit#213]
I have a REST interface that has an endpoint with an int? optional parameter. If I set the int parameter as null the endpoint is not called. However if I remove the int parameter when calling the endpoint it works fine. 

Is there way to remove optional parameters from the call if they are not set?

**Comment by airwareic** [comment]
I had this same problem. Looking through the code it seems that while you can format your value strings, you cannot remove the parameter. For example "/users?param={param}" with a null value would be sent over the wire as "/users?param=" whereas I believe you want "users/". If you trust that the server will accept the former format, and you're seeing problems with null values throwing for some reason, you can use a UriFormatter which you pass via RefitSettings.

To get around this in my own codebase, I made my own arguments class in which the ToString resolved using cached PropertyInfo's and would not stringify null properties:

```
public class GetParameters
{
    private readonly PropertyInfo[] _props;

    public int Limit { get; set; }
    public int Offset { get; set; }
    public int MyOptionalInt { get; set; }

    public GetParameters()
    {
        _props = this.GetType().GetProperties(BindingFlags.Public | BindingFlags.Instance);
    }

    public override string ToString()
    {
        var resolvedProps = new Dictionary<PropertyInfo, object>();
        foreach (var prop in _props)
        {
            var instValue = prop.GetValue(this);
            if (instValue != null)
                resolvedProps.Add(prop, instValue);
        }

        return string.Join(",", resolvedProps.Select(prop => string.Format("{0}={1}", prop.Key, prop.Value)));
    }
}
```

Hope that helps! I know it's not very pretty (also not super performant given the use of poorly cached property access delegates), but it does allow you to define your interface more easily because the attribution for each method becomes "/users?{param}" and it homogenizes your method signatures across all your CRUD operations.

**Comment by bennor** [comment]
@airwareic If you're getting `null` values sent as `?param=`, it's a bug, because [this isn't working](https://github.com/paulcbetts/refit/blob/master/Refit%2FRequestBuilderImplementation.cs#L131).

It's definitely not supposed to add `null` querystring parameters.

**Comment by airwareic** [comment]
@bennor: I took another look at creating a client. Just in case this had something to do with System.Nullable<T> vs. classes I implemented it both ways. Each time I got the same result:
![image](https://cloud.githubusercontent.com/assets/13759135/12257455/c89b9ec4-b8bb-11e5-94eb-4a5bd4bcfe4b.png)

Here's the code:
```
public interface IRefitTester
{
    [Get("/users?limit={limit}")]
    Task<IEnumerable<int>> GetStuff(int? limit = null);
}
```

**Comment by bennor** [comment]
Where's that exception being thrown? (What does the stack trace look like?)

**Comment by airwareic** [comment]
Here's the full trace:

   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at System.Text.RegularExpressions.Regex.Replace(String input, String pattern, String replacement, RegexOptions options)
   at Refit.RequestBuilderImplementation.<>c__DisplayClassc.<buildRequestFactoryForMethod>b__9(Object[] paramList) in y:\code\paulcbetts\refit\Refit\RequestBuilderImplementation.cs:line 86
   at Refit.RequestBuilderImplementation.<>c__DisplayClass2e`1.<<buildCancellableTaskFuncForMethod>b__2d>d__30.MoveNext() in y:\code\paulcbetts\refit\Refit\RequestBuilderImplementation.cs:line 314

**Comment by bennor** [comment]
Ah I see. You can fix that by changing your interface to:

```csharp
public interface IRefitTester
{
    [Get("/users")]
    Task<IEnumerable<int>> GetStuff(int? limit = null);
}
```

Any parameter which doesn't go anywhere else will be treated as a querystring parameter.

_I'm still not sure if this is the problem reported by @doorman02 though._

**Comment by airwareic** [comment]
Ahhh perfect! That's really good to know, and will really help clean up my code. Thanks!

**Comment by doorman02** [comment]
Great thanks!!
